### PR TITLE
Enable loading binary files, against master

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
### Description
Rebase of #27 against master.

### Checklist

- [ ] I have tested the code manually
- [x] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by abhi-agg** [comment]
@XapaJIaMnu Was it intentional or did you forget to add someone as a reviewer 😄 ?

**Comment by XapaJIaMnu** [comment]
> @XapaJIaMnu Was it intentional or did you forget to add someone as a reviewer  ?

I don't usually add people as reviewers, probably a bad habit of mine...

**Comment by abhi-agg** [comment]
So, who should be reviewing this code? May be @kpu ?

**Review by kpu — APPROVED** [review]
It's a dirty hack but so is upstream

**Pull request merged**
