### PR TITLE
Update intgemm: optional AVX2 support

### PR DESCRIPTION
**Pull request by kpu**
Updates intgemm to do a compiler test for AVX2 support.  This is progress towards #5 and partly addresses compile errors in #6 .  

### Description
I've updated intgemm to add a compilation test for AVX2 support and macros to guard AVX2 usage.  

### How to test
Intentionally break the tests by adding garbage to files in `compile_tests`

### Checklist

- [x] I have tested the code manually

### CODE REVIEW

**Comment by kpu** [comment]
NB: windows builds are failing due to https://github.com/marian-nmt/marian-dev/issues/765 unrelated to this PR.

**Comment by andrenatal** [comment]
After having this PR applied into #6, some errors are gone. Please see https://github.com/browsermt/marian-dev/pull/6#issuecomment-729311962

**Comment by abhi-agg** [comment]
As CI is green and windows build failure is unrelated to this change, let's merge it.

**Review by abhi-agg — APPROVED** [review]
As CI is green and windows build failure is unrelated to this change, let's merge it.

**Comment by abhi-agg** [comment]
@kpu Can we merge this change?

**Pull request merged**
