### PR TITLE
QE - Distilled Model

### PR DESCRIPTION
**Pull request by felipesantosk**
This PR has the marian changes related to the [browsermt QE distilled model PR](https://github.com/browsermt/bergamot-translator/pull/364)

This PR is not ready for production. For now it's just for test and debug.

List of changes:
- Save the debug tensor in a container.
- GRUCell - Changes the expected parameters
- GRUCell - Adds a hidden bias on the operation

### CODE REVIEW

**Comment by graemenail** [comment]
Hi @felipesantosk thanks for opening the PR here. I've marked it as draft so it's clear that it's not ready yet.

Continuing from https://github.com/felipesantosk/bergamot-translator/issues/2, I believe the problem is the layout of the tensor you pass to the RNN. It should be `{dimTime, dimBatch, dimEmb}`. If you transpose `{1,0,2}` on the input, and the same on the output, and it should give you the results you posted on the other PR.

**Comment by felipesantosk** [comment]
@graemenail , I added the transpose and it worked perfectly. Thanks a lot.  Let me ask you something, What do you think about this additional bias parameter, the hidden bias (bu_)?  Could be added as an optional parameter at GRU Cell? The other parameters, I think it is possible to split them to work as expected in the current code.

**Comment by jerinphilip** [comment]
> What do you think about this additional bias parameter, the hidden bias (bu_)? Could be added as an optional parameter at GRU Cell?

Some prior models may expect GRUCell to remain as is. There are two ways I immediately see:

1. Add a `bool` switch something like `GRU(50, 50, bidirectional=True, hidden_bias=False)`, so it does not break previous code and you can configure via a parameter at construction. This could however mean the bias vector is allocated even when it's not needed, unless there's that possibility in code - which may not be preferable.
2. Duplicate a `TorchGRU` cell from the `GRU` and set it to include bias.

**Comment by graemenail** [comment]
I think @jerinphilip summarised it well. I don't immediately see an issue an issue with optional parameters (as an example, see the params for LayerNorm in the GRU constructor). 

I think there's an scope in both these approaches to reuse code. To have parity with the torch implementation we need to add the bias. Implementing by adding it to `sU`, as you did, enables us to use `gruOps`, provided we to ensure that `final_` is set to `false` to use the `else` codepath `GRUFastForward` (via `gruOps`):
```cpp
if(final)
  h = std::tanh(xWrow[l] + (sUrow[l] + b[l]) * r);
else
  h = std::tanh(xWrow[l] + sUrow[l] * r + b[l]);
```

We also need this to be configurable somewhere. At minimum this would be in the options you pass to `encoderS2S` for QE. However, this would only be accessible to people using Marian as a library. If we want to expose it through the CLI, then we have: a) e.g. `--gru-hidden-bias true`, or  b) e.g. `--enc-cell gru-torch`; personally, I think **a** is a bit too specific.  

Regarding options 1 or 2: the advantage of approach 1 is that we wouldn't have to duplicate the GRU cell implementation and risk them falling out of sync at a later date. However, GRU is the default option for enc/dec-cells - so we should be careful modifying it. We should be confident that we do not change the current behaviour, and this crucial if we want to have this change upstream later.

**Comment by felipesantosk** [comment]
@graemenail  @jerinphilip , Thanks for the suggestions. 

> Add a bool switch something like GRU(50, 50, bidirectional=True, hidden_bias=False), so it does not break previous code and you can configure via a parameter at construction. This could however mean the bias vector is allocated even when it's not needed, unless there's that possibility in code - which may not be preferable.

For now, I followed the first approach, but we can decide the best approach later.

**Comment by XapaJIaMnu** [comment]
Ended up not being used, sorry :/

**Pull request closed without merging**
